- name: ec2 launcher
  hosts: localhost
  connection: local
  tasks:
  - name: launching ec2
    ec2:
      aws_access_key: <your access key>
      aws_secret_key: <your secret key> 
      instance_type: t2.micro
      key_name: <Your pem file>
      image: ami-03b6f27628a4569c8
      region: ap-southeast-1
      group: default
      count: 1
      vpc_subnet_id: subnet-70415c39
      wait: yes
      assign_public_ip: yes

